name: pixl.js-fw

on:
  push:
    branches: [ "main", "ble", "ci" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: solosky/nrf52-sdk:latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: build bootloader
      run: cd fw/bootloader && make
    - name: build firmware
      run: cd fw && make
    - name: build ota
      run: cd fw && make ota APP_VERSION=$GITHUB_RUN_NUMBER
    - name: build all
      run: cd fw && make full
    - name: upload bootloader
      uses: actions/upload-artifact@v3
      with:
        name: pixljs_firmware
        path: fw/bootloader/_build/bootloader.hex
    - name: upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: pixljs_firmware
        path: fw/_build/pixljs.hex
    - name: upload all
      uses: actions/upload-artifact@v3
      with:
        name: pixljs_firmware
        path: fw/_build/pixljs_all.hex
    - name: upload ota 
      uses: actions/upload-artifact@v3
      with:
        name: pixljs_firmware
        path: fw/_build/pixjs_ota_v${{github.run_number}}.zip