name: pixl.js-fw

on:
  push:
    branches: [ "main", "ble", "ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: solosky/nrf52-sdk:latest
    steps:
    - uses: actions/checkout@v3
    - name: build_bootloader
      run: cd fw/bootloader && make
