name: C/C++ CI

on:
  push:
    branches: [ "main", "ble", "ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:14.16
    steps:
    - uses: actions/checkout@v3
