name: pixl.js-fw

on:
  push:
    branches: [ "main", "ble", "ci" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: solosky/nrf52-sdk:latest
    steps:
    - uses: actions/checkout@v3
      submodules: true

    - name: build bootloader
      run: cd fw/bootloader && make
    - name: build firmware
      run: cd fw && make
    - name: build ota
      run: cd fw & make ota APP_VERSION=${{ env.GITHUB_RUN_NUMBER }}
    - name: upload bootloader
      uses: actions/upload-artifact@v3
      with:
        name: pixl.js_bootloaderwg
        path: bootloader/_build/bootloader.hex
    - name: upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: pixljs_firmware
        path: _build/pixljs.hex
    - name: upload ota 
      uses: actions/upload-artifact@v3
      with:
        name: pixljs_firmware
        path: _build/pixjs_ota_v${{ env.GITHUB_RUN_NUMBER }}.zip